
#include "ikey.h"

#define def(X, Y) [X] = Y

char* MNEM[] = {
    //order like in the instruction summary

    //arithmetic and logic instructions
    def(AVR_ADD, "add"),
    def(AVR_ADC, "adc"),
    def(AVR_ADIW, "adiw"),
    def(AVR_SUB, "sub"),
    def(AVR_SUBI, "subi"),
    def(AVR_SBC, "sbc"),
    def(AVR_SBCI, "sbci"),
    def(AVR_SBIW, "sbiw"),
    def(AVR_AND, "and"),
    def(AVR_ANDI, "andi"),
    def(AVR_OR, "or"),
    def(AVR_ORI, "ori"),
    def(AVR_EOR, "eor"),
    def(AVR_COM, "com"),
    def(AVR_NEG, "neg"),
    def(AVR_SBR, "sbr"),
    def(AVR_CBR, "cbr"),
    def(AVR_INC, "inc"),
    def(AVR_DEC, "dec"),
    def(AVR_TST, "tst"),
    def(AVR_CLR, "clr"),
    def(AVR_SER, "ser"),
    def(AVR_MUL, "mul"),
    def(AVR_MULS, "muls"),
    def(AVR_MULSU, "mulsu"),
    def(AVR_FMUL, "fmul"),
    def(AVR_FMULS, "fmuls"),
    def(AVR_FMULSU, "fmulsu"),
    def(AVR_DES, "des"),

    //branch instructions
    def(AVR_RJMP, "rjmp"),
    def(AVR_IJMP, "ijmp"),
    def(AVR_EIJMP, "eijmp"),
    def(AVR_JMP, "jmp"),
    def(AVR_RCALL, "rcall"),
    def(AVR_ICALL, "icall"),
    def(AVR_EICALL, "eicall"),
    def(AVR_CALL, "call"),
    def(AVR_RET, "ret"),
    def(AVR_RETI, "reti"),
    def(AVR_CPSE, "cpse"),
    def(AVR_CP, "cp"),
    def(AVR_CPC, "cpc"),
    def(AVR_CPI, "cpi"),
    def(AVR_SBRC, "sbrc"),
    def(AVR_SBRS, "sbrs"),
    def(AVR_SBIC, "sbic"),
    def(AVR_SBIS, "sbis"),
    def(AVR_BRBS, "brbs"),
    def(AVR_BRBC, "brbc"),
    def(AVR_BREQ, "breq"),
    def(AVR_BRNE, "brne"),
    def(AVR_BRCS, "brcs"),
    def(AVR_BRCC, "brcc"),
    def(AVR_BRSH, "brsh"),
    def(AVR_BRLO, "brlo"),
    def(AVR_BRMI, "brmi"),
    def(AVR_BRPL, "brpl"),
    def(AVR_BRGE, "brge"),
    def(AVR_BRLT, "brlt"),
    def(AVR_BRHS, "brhs"),
    def(AVR_BRHC, "brhc"),
    def(AVR_BRTS, "brts"),
    def(AVR_BRTC, "brtc"),
    def(AVR_BRVS, "brvs"),
    def(AVR_BRVC, "brvc"),
    def(AVR_BRIE, "brie"),
    def(AVR_BRID, "brid"),

    //data transfer instructions
    def(AVR_MOV, "mov"),
    def(AVR_MOVW, "movw"),
    def(AVR_LDI, "ldi"),

    def(AVR_LDS, "lds"),

    //ld instructions
    def(AVR_LDX, "ld"),
    def(AVR_LDXpostInc, "ld"),
    def(AVR_LDY, "ld"),
    def(AVR_LDYpostInc, "ld"),
    def(AVR_LDZ, "ld"),
    def(AVR_LDZpostInc, "ld"),
    def(AVR_LDDY, "ldd"),
    def(AVR_LDDZ, "ldd"),

    def(AVR_STS, "sts"),

    //st instructions
    def(AVR_STX, "st"),
    def(AVR_STXPLUS, "st"),
    def(AVR_STY, "st"),
    def(AVR_STZ, "st"),
    def(AVR_STDY, "std"),

    def(AVR_LPM, "lpm"),
    def(AVR_ELPM, "elpm"),
    def(AVR_SPM, "spm"),
    def(AVR_IN, "in"),
    def(AVR_OUT, "out"),
    def(AVR_PUSH, "push"),
    def(AVR_POP, "pop"),
    def(AVR_XCH, "xch"),
    def(AVR_LAS, "las"),
    def(AVR_LAC, "lac"),
    def(AVR_LAT, "lat"),

    //bit and bit-test instructions
    def(AVR_LSL, "lsl"),
    def(AVR_LSR, "lsr"),
    def(AVR_ROL, "rol"),
    def(AVR_ROR, "ror"),
    def(AVR_ASR, "asr"),
    def(AVR_SWAP, "swap"),
    def(AVR_SBI, "sbi"),
    def(AVR_CBI, "cbi"),

    def(AVR_BST, "bst"),
    def(AVR_BLD, "bld"),
    def(AVR_BSET, "bset"),
    def(AVR_BCLR, "bclr"),
    def(AVR_SEC, "sec"),
    def(AVR_CLC, "clc"),
    def(AVR_SEN, "sen"),
    def(AVR_CLN, "cln"),
    def(AVR_SEZ, "sez"),
    def(AVR_CLZ, "clz"),
    def(AVR_SEI, "sei"),
    def(AVR_CLI, "cli"),
    def(AVR_SES, "ses"),
    def(AVR_CLS, "cls"),
    def(AVR_SEV, "sev"),
    def(AVR_CLV, "clv"),
    def(AVR_SET, "set"),
    def(AVR_CLT, "clt"),
    def(AVR_SEH, "seh"),
    def(AVR_CLH, "clh"),

    //mcu control instructions
    def(AVR_BREAK, "break"),
    def(AVR_NOP, "nop"),
    def(AVR_SLEEP, "sleep"),
    def(AVR_WDR, "wdr"),

    // --- START X86 Instructions
    [X86_MOV_CONST] = "mov",
    [X86_MOV_REGS] = "mov",
    [X86_MOV_LOAD] = "mov",
    [X86_MOV_STORE] = "mov",
    [X86_MOV_LOAD_WIDTH] = "mov",
    [X86_MOVZX_LOAD_WIDTH] = "movzx",
    [X86_MOVZX_REGS_WIDTH] = "movzx",
    [X86_MOV_STORE_WIDTH] = "mov",
    [X86_MOV_CONST_SYMBOL] = "mov",
    [X86_CMOVE] = "cmove",
    [X86_XCHG] = "xchg",
    [X86_PUSH] = "push",
    [X86_POP] = "pop",
    [X86_ADD] = "add",
    [X86_SUB] = "sub",
    [X86_IMUL] = "imul",
    [X86_MUL] = "mul",
    [X86_DIV] = "div",
    [X86_INC] = "inc",
    [X86_DEC] = "dec",
    [X86_NEG] = "neg",
    [X86_CMP] = "cmp",
    [X86_CMP_CONST] = "cmp",
    [X86_TEST] = "test",
    [X86_SETE] = "sete",
    [X86_AND] = "and",
    [X86_OR] = "or",
    [X86_XOR] = "xor",
    [X86_NOT] = "not",
    [X86_SHL] = "shl",
    [X86_SHR] = "shr",
    [X86_SAL] = "sal",
    [X86_SAR] = "sar",
    [X86_ROL] = "rol",
    [X86_ROR] = "ror",
    [X86_JMP] = "jmp",
    [X86_JE] = "je",
    [X86_JNE] = "jne",
    [X86_JG] = "jg",
    [X86_JGE] = "jge",
    [X86_JL] = "jl",
    [X86_JLE] = "jle",
    [X86_JZ] = "jz",
    [X86_CALL] = "call",
    [X86_ICALL] = "call",
    [X86_RET] = "ret",
    [X86_NOP] = "nop",
    [X86_INT] = "int",
    [X86_SYSCALL] = "syscall",
    // --- END X86 Instructions

};
