# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  build-job-ubuntu-2004:
    machine:
      image: ubuntu-2004:2022.10.1
    steps:
      - checkout
      - run: sudo apt-get update && sudo apt install -y gcc make cmake valgrind flex avra
      - run:
          name: "build"
          command: |
            echo 'export PATH=/home/circleci/project/lexer/build:/home/circleci/project/parser/build:/home/circleci/project/compiler:"$PATH"' >> "$BASH_ENV"
            source "$BASH_ENV"
            echo "PATH is: $PATH"
            make
  build-job-ubuntu-2204:
    machine:
      image: ubuntu-2204:2022.10.2
    #docker:
    #  - image: cimg/base:stable
    # Add steps to the job
    # See: https://circleci.com/docs/2.0/configuration-reference/#steps
    steps:
      - checkout
      - run: sudo apt-get update && sudo apt install -y gcc make cmake valgrind flex avra
      - run:
          name: "build"
          command: |
            echo 'export PATH=/home/circleci/project/lexer/build:/home/circleci/project/parser/build:/home/circleci/project/compiler:"$PATH"' >> "$BASH_ENV"
            source "$BASH_ENV"
            echo "PATH is: $PATH"
            make

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  build-workflow:
    jobs:
      - build-job-ubuntu-2004
      - build-job-ubuntu-2204
