all: libvmcu-Virtual-MCU-Library 
	cd libvmcu-Virtual-MCU-Library/build-release; make -f build.mk; cd ../..

libvmcu-Virtual-MCU-Library:
	git clone https://github.com/Milo-D/libvmcu-Virtual-MCU-Library.git

#flex-2.6.4.tar.gz:
#	wget https://github.com/westes/flex/files/981163/flex-2.6.4.tar.gz
#	tar -xf flex-2.6.4.tar.gz
#	cd flex-2.6.4.tar.gz; ./configure && make; cd ..
