all: libvmcu-Virtual-MCU-Library
	cd libvmcu-Virtual-MCU-Library/build-release; make -f build.mk; cd ../..

libvmcu-Virtual-MCU-Library:
	git clone https://github.com/Milo-D/libvmcu-Virtual-MCU-Library.git

