name: W3CValidation

on:
  pull_request:
    paths:
      - 'docs/**'

permissions:
  contents: read

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: HTML5Validator
        uses: Cyb3r-Jak3/html5validator-action@v7.2.0
        with:
          root: docs/
          blacklist: "googlec8c33fc0ae3784b9.html"

